[package]
name = "foolang"
version = "0.1.0"
authors = ["Filip Andersson"]
edition = "2018"
description  = "A toy programing language as a learning exercise."
license-file = "LICENCE"

[workspace]
members = [
    "crates/lexer",
]

[profile.dev]
debug = 0

[profile.release]
lto="thin"
