[package]
name = "parser"
version = "0.1.0"
authors = ["Filip Andersson"]
edition = "2018"


[dependencies]
lexer = { path = "../lexer" }
types = { path = "../types" }

rowan = "0.12"
num = "0.4"
num-traits = "0.2"
num-derive = "0.3"
